image: python:3.8

before_script:
  - python --version
  
stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install -y python-dev python-pip
  - pip install pipenv
  - pipenv install
  - pipenv run python -m pytest
  - pipenv run coverage run --source=messagebird -m unittest discover -s tests/
  - pipenv run coverage report --fail-under=80
  - pipenv run pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./messagebird/
  - pipenv run pycodestyle --statistics --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,E501 ./tests/