image: python:3.8

before_script:
  - python --version
  
stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install -y python-dev python-pip
  - pip install pipenv
  - pipenv install
  - pipenv run python -m pytest